### ISSUE TITLE
[Bug]: C120 Indoor Camera doesn't show video on Homekit connected to Homebase

### ISSUE THREAD

**Issue by UnknownReverence** [homebridge-plugins/homebridge-eufy-security#725]
### What happened?

Apparently when I have my C120 camera connected to the homebase the live feed video won't work. I connect it directly to the router and it works fine with homekit.

Has anyone else had this issue or know how to resolve it? I'd like it to be connected to my homebase if I could.

Currently on Homebridge 1.11.1, Node 24.12.0, and plugin version 4.3.7, running it all on Unraid

My Doorbell E340 seems to be working fine and it didn't work when it wasn't connected to my Homebase before I got it.

### Device Type

Indoor Camera (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Other (UnSupported)

### Relevant log output

```shell
[12/26/2025, 22:44:09]  [EufySecurity]  ERROR   Indoor Livestream timeout: No livestream emitted within the expected timeframe.
[12/26/2025, 22:44:09]  [EufySecurity]  WARN    Indoor If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[12/26/2025, 22:44:09]  [EufySecurity]  WARN    Indoor Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[12/26/2025, 22:44:09]  [EufySecurity]  ERROR   Indoor Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
```

### config

```shell
{
            "platform": "EufySecurity",
            "name": "EufySecurity",
            "username": "***",
            "password": "***",
            "deviceName": "",
            "enableDetailedLogging": false,
            "omitLogFiles": false,
            "CameraMaxLivestreamDuration": 30,
            "pollingIntervalMinutes": 10,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "ignoreStations": [],
            "ignoreDevices": [],
            "country": "US",
            "stations": [],
            "cameras": [
                {
                    "serialNumber": "***",
                    "videoConfig": {
                        "audio": true,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 15,
                        "useSeparateProcesses": true
                    },
                    "snapshotHandlingMethod": 3
                }
            ],
            "cleanCache": true,
            "ignoreMultipleDevicesWarning": false,
            "autoSyncStation": false,
            "enableEmbeddedPKCS1Support": true,
            "_bridge": {
                "username": "***",
                "port": ***,
                "name": "Homebridge Eufy Security"
            }
        }
```

**Comment by lenoxys** [comment]
Hi @UnknownReverence,

Thanks for reporting this issue.

Could you please test the latest beta version (**4.4.2-beta.7**) we've released? You can install it with:

```
npm install homebridge-eufy-security@4.4.2-beta.7
```

This beta works with the latest bropat eufy-security-client library, which includes a lot of fixes concerning the Homebase communication. The PKCS1 issue you're encountering should no longer require the \`enableEmbeddedPKCS1Support\` workaround — **please make sure to disable it** (set \`\"enableEmbeddedPKCS1Support\": false\` or remove it from your config) when testing.

Let me know if this resolves your livestream issue with the C120 connected to the Homebase!

**Comment by UnknownReverence** [comment]
I'm also seeing a beta 10. Just the 7 or should I just go up to 10?

**Comment by lenoxys** [comment]
try the latest as well

**Comment by UnknownReverence** [comment]
C120 Indoor cam is still not responding.

It works when it's not connected to Homebase still.

**Comment by lenoxys** [comment]
@UnknownReverence which homebase are you using ?

**Comment by UnknownReverence** [comment]
Homebase 3

**Comment by lenoxys** [comment]
I might have a lead on the root cause — it can be related to how the P2P encryption key exchange works in the underlying library for newer standalone devices like the E340.

To validate my fix, I'd need to test against an actual C120 Indoor device. Would one of you be willing to temporarily share your device with the following Eufy account?

[homebridge.eufy.sec@gmail.com](mailto:homebridge.eufy.sec@gmail.com)

Please also let me know which country your account is registered in.

This is entirely optional — no obligation. I understand sharing device access requires trust. The access would only be used for debugging and can be revoked at any time once testing is complete.

**Comment by UnknownReverence** [comment]
How long would you need access for? I don't use my indoor camera too much and I can make it so nothing can be seen.

**Comment by lenoxys** [comment]
I will need for a maximum a week and you can revoked it at any time. 

Please also let me know which country your account is registered in.

**Comment by lenoxys** [comment]
hello can you test on 4.5.1 latest beta ?

**Comment by UnknownReverence** [comment]
Yeah, I can try in a little. Been a bit busy and going back and forth putting the camera on homebase and taking it off if it doesn't work takes a little since I have to delete the camera and scan it again.

**Comment by UnknownReverence** [comment]
> hello can you test on 4.5.1 latest beta ?

Sorry for the late reply, but I don't have an option for anything higher than 4.4.2 beta 54

**Comment by lenoxys** [comment]
You will need to migrate the plugin to the scoped version. When on the plugin list, click on the violet icon piper right corner and follow the migration path.

**Comment by UnknownReverence** [comment]
It's on 4.6.1 now and still getting that the camera is not responding and not able to see it.

**Comment by lenoxys** [comment]
Can you try latest beta 4.6.2 ?

**Comment by UnknownReverence** [comment]
Still an error. 

<img width="660" height="1434" alt="Image" src="https://github.com/user-attachments/assets/88b9f4ed-7b52-4c00-9507-58547af36457" />

**Comment by lenoxys** [comment]
**This project is currently frozen.**

The plugin relies on [`eufy-security-client`](https://github.com/bropat/eufy-security-client), which its maintainer has **deprecated**. Eufy has moved its apps to a new **"Mega"** protocol, and a brand-new library is being built against it. All development effort is going there.

What this means for now:
- ✅ The current version keeps working as-is for devices still on the old protocol.
- 🧊 No new features or new device support can be added.
- 🩹 Only strictly necessary fixes for critical breakages will be considered.
- 🚀 Effort is focused on the new Mega-protocol library first. Work to adopt it in this plugin **has not started yet**.

**ETA:** work on this plugin is not expected to begin before **mid-August 2026**, and only once the underlying library is ready.

Because of this, I'm closing existing issues and pull requests to reflect the current status. This is not a reflection on your report — I simply cannot action it right now.

Please watch the repository and the upstream [deprecation notice](https://github.com/bropat/eufy-security-client) for updates.

💬 For questions and discussion, join us on [Discord](https://discord.gg/jc8FSjqQAN).

Thank you for your patience. 🙏
